#!/usr/bin/env bash
# Xfer file to web-01 server
# 4 parameters: file, host, user, password
# $0 - script name
# $1 - file name
# $2 - host
# $3 - user
# $4 - ssh key

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
