#!/usr/bin/env bash
##while loop with if and elif##
i=0
while [ $i -lt 10 ]
do
if  [ $i ==  3 ];
then
   echo -e "bad luck"
   
elif  [ $i == 7 ];
then
echo "good luck"
else 
	echo "Holberton School"
fi
((i++))
done
