#!/usr/bin/env bash
##while loop with if and elif##
i=0
while [ $i -lt 10 ]
do
echo "Holberton School"
 ((i++))
if  [[ "$i" == "3" ]];
then
   echo -e "bad luck"
   ((i++))
elif  [[ "$i" == "7" ]];
then 
echo "good luck"
fi
done
