#!/usr/bin/env bash
##COUNT AND PRINT
c=0
while [ $c -le 20 ]
do 
	echo "$c"
	((c++))
	case $c in
		5) echo "bad luck from China";;
			10) echo "bad luck from Japan";;
			18) echo ""bad luck from Italy;;
			*)
		esac

	
done
