#!/usr/bin/env bash
#  Install nginx on your web-01 server
find="^\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://918dcx.com;\n\t}\n\n\tlocation / {"
replace404="\terror_page 404 /error404.html;\n\n\tadd_header X-Served-By $hostname;\n\n\tlocation / {"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i "s@$find@$replace@" /etc/nginx/sites-available/default
sudo sed -i "s@$find@$replace404@" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
